version: "3.8"

services:
  mongodb:
    image: mongo:6
    container_name: todo-mongodb-prod
    restart: unless-stopped
    environment:
      MONGO_INITDB_DATABASE: todo-app
    volumes:
      - mongodb_data:/data/db
    networks:
      - todo-network

  backend:
    image: ${DOCKER_USERNAME:-username}/todo-backend:latest
    container_name: todo-backend-prod
    restart: unless-stopped
    environment:
      - MONGODB_URI=mongodb://mongodb:27017/todo-app
      - PORT=5000
    depends_on:
      - mongodb
    networks:
      - todo-network

  frontend:
    image: ${DOCKER_USERNAME:-username}/todo-app:latest
    container_name: todo-frontend-prod
    restart: unless-stopped
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - todo-network

networks:
  todo-network:
    driver: bridge

volumes:
  mongodb_data:
